version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  backend:
    container_name: app_backend
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: gihyung123
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
  # mysql:
  #   platform: linux/x86_64
  #   build: ./mysql
  #   restart: always
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypotint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: asdf
  #     MYSQL_DATABASE: myapp
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3000:80"